// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(SoeBackendContext))]
    [Migration("20250824170230_AddDescriptionToBookEntity")]
    partial class AddDescriptionToBookEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("BookId", "GenreId")
                        .HasName("book_genres_pkey");

                    b.HasIndex("GenreId");

                    b.ToTable("book_genres", (string)null);
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("BookId", "TagId")
                        .HasName("book_tags_pkey");

                    b.HasIndex("TagId");

                    b.ToTable("book_tags", (string)null);
                });

            modelBuilder.Entity("Favorite", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("BookId", "UserId")
                        .HasName("favorites_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.BookEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("book_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Annotation")
                        .HasColumnType("text")
                        .HasColumnName("annotation");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("book_name");

                    b.Property<string>("CoverId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cover_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<bool>("IsAdultContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_adult_content");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.HasKey("BookId")
                        .HasName("books_pkey");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("StatusId");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.BookPartEntity", b =>
                {
                    b.Property<Guid>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("part_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<string>("ContentPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_path");

                    b.Property<int?>("CountOfEndings")
                        .HasColumnType("integer")
                        .HasColumnName("count_of_endings");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_name");

                    b.Property<int>("PartOrder")
                        .HasColumnType("integer")
                        .HasColumnName("part_order");

                    b.HasKey("PartId")
                        .HasName("book_parts_pkey");

                    b.HasIndex("BookId");

                    b.HasIndex(new[] { "ContentPath" }, "book_parts_content_path_key")
                        .IsUnique();

                    b.ToTable("book_parts", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.BookStatisticEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<int?>("FavoriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("favorite_count");

                    b.Property<decimal?>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating")
                        .HasDefaultValueSql("0.00");

                    b.Property<int?>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<int?>("ReadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("read_count");

                    b.HasKey("BookId")
                        .HasName("book_statistics_pkey");

                    b.ToTable("book_statistics", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.BookStatusEntity", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("book_statuses_pkey");

                    b.HasIndex(new[] { "StatusName" }, "book_statuses_status_name_key")
                        .IsUnique();

                    b.ToTable("book_statuses", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.BookmarkEntity", b =>
                {
                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("BookmarkTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("bookmark_type_id");

                    b.HasKey("BookId", "UserId", "BookmarkTypeId")
                        .HasName("bookmarks_pkey");

                    b.HasIndex("BookmarkTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.BookmarkTypeEntity", b =>
                {
                    b.Property<int>("BookmarkTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookmark_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookmarkTypeId"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.HasKey("BookmarkTypeId")
                        .HasName("bookmark_types_pkey");

                    b.HasIndex(new[] { "DisplayName" }, "bookmark_types_display_name_key")
                        .IsUnique();

                    b.ToTable("bookmark_types", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment_text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("CommentId")
                        .HasName("comments_pkey");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.CommentLikeEntity", b =>
                {
                    b.Property<Guid>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("like_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LikeId")
                        .HasName("comment_likes_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CommentId", "UserId" }, "comment_likes_comment_id_user_id_key")
                        .IsUnique();

                    b.ToTable("comment_likes", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.EntityTypeEntity", b =>
                {
                    b.Property<int>("EntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entity_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntityTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("table_name");

                    b.HasKey("EntityTypeId")
                        .HasName("entity_types_pkey");

                    b.HasIndex(new[] { "TableName" }, "entity_types_table_name_key")
                        .IsUnique();

                    b.ToTable("entity_types", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.GenreEntity", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre_name");

                    b.HasKey("GenreId")
                        .HasName("genres_pkey");

                    b.HasIndex(new[] { "GenreName" }, "genres_genre_name_key")
                        .IsUnique();

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.IssueEntity", b =>
                {
                    b.Property<Guid>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IssueText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("issue_text");

                    b.Property<int?>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("IssueId")
                        .HasName("issues_pkey");

                    b.HasIndex("BookId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("issues", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.IssueResponseEntity", b =>
                {
                    b.Property<Guid>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("response_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ResponseId")
                        .HasName("issue_responses_pkey");

                    b.HasIndex("IssueId");

                    b.HasIndex("UserId");

                    b.ToTable("issue_responses", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.IssueStatusEntity", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId")
                        .HasName("issue_statuses_pkey");

                    b.HasIndex(new[] { "StatusName" }, "issue_statuses_status_name_key")
                        .IsUnique();

                    b.ToTable("issue_statuses", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.LanguageEntity", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("language_name")
                        .HasDefaultValueSql("'Russian'::character varying");

                    b.HasKey("LanguageId")
                        .HasName("languages_pkey");

                    b.HasIndex(new[] { "LanguageName" }, "languages_language_name_key")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<int?>("EntityTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type_id");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("NotificationText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notification_text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notifications_pkey");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.PartEndingEntity", b =>
                {
                    b.Property<int>("EndingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ending_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EndingId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EndingDescription")
                        .HasColumnType("text")
                        .HasColumnName("ending_description");

                    b.Property<string>("EndingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ending_name");

                    b.Property<int>("EndingOrder")
                        .HasColumnType("integer")
                        .HasColumnName("ending_order");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.HasKey("EndingId")
                        .HasName("part_endings_pkey");

                    b.HasIndex(new[] { "PartId" }, "idx_part_endings_part");

                    b.ToTable("part_endings", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.ReadingStatisticEntity", b =>
                {
                    b.Property<Guid>("ReadingStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reading_stat_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<DateTime?>("LastReadTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_read_time");

                    b.Property<decimal?>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("progress")
                        .HasDefaultValueSql("0.00");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<DateTime?>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("TimeSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("time_spent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ReadingStatId")
                        .HasName("reading_statistics_pkey");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("reading_statistics", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex(new[] { "UserId", "Token" }, "idx_refresh_tokens_active")
                        .HasFilter("(is_revoked = false)");

                    b.HasIndex(new[] { "Token" }, "idx_refresh_tokens_token");

                    b.HasIndex(new[] { "UserId" }, "idx_refresh_tokens_user_id");

                    b.HasIndex(new[] { "Token" }, "refresh_tokens_token_key")
                        .IsUnique();

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.SortOptionEntity", b =>
                {
                    b.Property<int>("SortOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sort_option_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SortOptionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order");

                    b.HasKey("SortOptionId")
                        .HasName("sort_options_pkey");

                    b.HasIndex(new[] { "Name" }, "sort_options_name_key")
                        .IsUnique();

                    b.ToTable("sort_options", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.TagEntity", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tag_name");

                    b.HasKey("TagId")
                        .HasName("tags_pkey");

                    b.HasIndex(new[] { "TagName" }, "tags_tag_name_key")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("avatar_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "RoleId" }, "idx_users_role");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex(new[] { "RoleName" }, "user_roles_role_name_key")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.UserStatisticEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("AverageReadingTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("average_reading_time");

                    b.Property<int?>("BooksRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("books_read");

                    b.Property<DateTime?>("LastActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_active")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("user_statistics_pkey");

                    b.ToTable("user_statistics", (string)null);
                });

            modelBuilder.Entity("Persistence.Entities.UserUnlockedEndingEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("EndingId")
                        .HasColumnType("integer")
                        .HasColumnName("ending_id");

                    b.Property<DateTime?>("UnlockedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "EndingId")
                        .HasName("user_unlocked_endings_pkey");

                    b.HasIndex(new[] { "EndingId" }, "idx_user_unlocked_endings_ending");

                    b.HasIndex(new[] { "UserId" }, "idx_user_unlocked_endings_user");

                    b.ToTable("user_unlocked_endings", (string)null);
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("book_genres_book_id_fkey");

                    b.HasOne("Persistence.Entities.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("book_genres_genre_id_fkey");
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("book_tags_book_id_fkey");

                    b.HasOne("Persistence.Entities.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("book_tags_tag_id_fkey");
                });

            modelBuilder.Entity("Favorite", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorites_book_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("favorites_user_id_fkey");
                });

            modelBuilder.Entity("Persistence.Entities.BookEntity", b =>
                {
                    b.HasOne("Persistence.Entities.UserEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("books_author_id_fkey");

                    b.HasOne("Persistence.Entities.LanguageEntity", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .IsRequired()
                        .HasConstraintName("books_language_id_fkey");

                    b.HasOne("Persistence.Entities.BookStatusEntity", "Status")
                        .WithMany("Books")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("books_status_id_fkey");

                    b.Navigation("Author");

                    b.Navigation("Language");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Persistence.Entities.BookPartEntity", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", "Book")
                        .WithMany("BookParts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("book_parts_book_id_fkey");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Persistence.Entities.BookStatisticEntity", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", "Book")
                        .WithOne("BookStatistic")
                        .HasForeignKey("Persistence.Entities.BookStatisticEntity", "BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("book_statistics_book_id_fkey");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Persistence.Entities.BookmarkEntity", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", "Book")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookmarks_book_id_fkey");

                    b.HasOne("Persistence.Entities.BookmarkTypeEntity", "BookmarkType")
                        .WithMany("Bookmarks")
                        .HasForeignKey("BookmarkTypeId")
                        .IsRequired()
                        .HasConstraintName("bookmarks_bookmark_type_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookmarks_user_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("BookmarkType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.CommentEntity", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", "Book")
                        .WithMany("Comments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comments_book_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comments_user_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.CommentLikeEntity", b =>
                {
                    b.HasOne("Persistence.Entities.CommentEntity", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comment_likes_comment_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("CommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("comment_likes_user_id_fkey");

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.IssueEntity", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", "Book")
                        .WithMany("Issues")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("issues_book_id_fkey");

                    b.HasOne("Persistence.Entities.IssueStatusEntity", "Status")
                        .WithMany("Issues")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("issues_status_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("Issues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("issues_user_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.IssueResponseEntity", b =>
                {
                    b.HasOne("Persistence.Entities.IssueEntity", "Issue")
                        .WithMany("IssueResponses")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("issue_responses_issue_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("IssueResponses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("issue_responses_user_id_fkey");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.NotificationEntity", b =>
                {
                    b.HasOne("Persistence.Entities.EntityTypeEntity", "EntityType")
                        .WithMany("Notifications")
                        .HasForeignKey("EntityTypeId")
                        .HasConstraintName("notifications_entity_type_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("EntityType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.PartEndingEntity", b =>
                {
                    b.HasOne("Persistence.Entities.BookPartEntity", "Part")
                        .WithMany("PartEndings")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("part_endings_part_id_fkey");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Persistence.Entities.ReadingStatisticEntity", b =>
                {
                    b.HasOne("Persistence.Entities.BookEntity", "Book")
                        .WithMany("ReadingStatistics")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("reading_statistics_book_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("ReadingStatistics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("reading_statistics_user_id_fkey");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.HasOne("Persistence.Entities.UserRoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Persistence.Entities.UserStatisticEntity", b =>
                {
                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithOne("UserStatistic")
                        .HasForeignKey("Persistence.Entities.UserStatisticEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_statistics_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.UserUnlockedEndingEntity", b =>
                {
                    b.HasOne("Persistence.Entities.PartEndingEntity", "Ending")
                        .WithMany("UserUnlockedEndings")
                        .HasForeignKey("EndingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_unlocked_endings_ending_id_fkey");

                    b.HasOne("Persistence.Entities.UserEntity", "User")
                        .WithMany("UserUnlockedEndings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_unlocked_endings_user_id_fkey");

                    b.Navigation("Ending");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Persistence.Entities.BookEntity", b =>
                {
                    b.Navigation("BookParts");

                    b.Navigation("BookStatistic");

                    b.Navigation("Bookmarks");

                    b.Navigation("Comments");

                    b.Navigation("Issues");

                    b.Navigation("ReadingStatistics");
                });

            modelBuilder.Entity("Persistence.Entities.BookPartEntity", b =>
                {
                    b.Navigation("PartEndings");
                });

            modelBuilder.Entity("Persistence.Entities.BookStatusEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Persistence.Entities.BookmarkTypeEntity", b =>
                {
                    b.Navigation("Bookmarks");
                });

            modelBuilder.Entity("Persistence.Entities.CommentEntity", b =>
                {
                    b.Navigation("CommentLikes");
                });

            modelBuilder.Entity("Persistence.Entities.EntityTypeEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Persistence.Entities.IssueEntity", b =>
                {
                    b.Navigation("IssueResponses");
                });

            modelBuilder.Entity("Persistence.Entities.IssueStatusEntity", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("Persistence.Entities.LanguageEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Persistence.Entities.PartEndingEntity", b =>
                {
                    b.Navigation("UserUnlockedEndings");
                });

            modelBuilder.Entity("Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Books");

                    b.Navigation("CommentLikes");

                    b.Navigation("Comments");

                    b.Navigation("IssueResponses");

                    b.Navigation("Issues");

                    b.Navigation("Notifications");

                    b.Navigation("ReadingStatistics");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserStatistic");

                    b.Navigation("UserUnlockedEndings");
                });

            modelBuilder.Entity("Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
